title: "Operating System Configuration, Security & Performance Journal"
description: "CMPN2022 Technical Journal â€“ University of Roehampton"
theme: jekyll-theme-slate
markdown: kramdown

# Custom styling
include:
  - styles.css
